name: ci-test

on: [push, pull_request]

jobs:

  test:
    name: Test
    runs-on: ubuntu-18.04

    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.15
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Test
      run: make test
